kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc
reclaimPolicy: Retain 
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-0e4ea8eaaf2c5d99a
  directoryPerms: "700"
  basePath: "/roboshop"
  